# Generated by Django 4.2.7 on 2024-02-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="defectType",
            fields=[
                ("sDefectTypeID", models.AutoField(primary_key=True, serialize=False)),
                ("sDefectTypeName", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="handrail",
            fields=[
                (
                    "sHandrailID",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="Item #"
                    ),
                ),
                (
                    "sHandrailCode",
                    models.CharField(max_length=50, verbose_name="Handrail Code"),
                ),
                ("sLine", models.CharField(max_length=50, verbose_name="Line")),
                ("sStation", models.CharField(max_length=50, verbose_name="Station")),
                ("sEscNo", models.PositiveIntegerField(verbose_name="Escalator No.")),
                ("sPosition", models.CharField(max_length=10, verbose_name="Position")),
            ],
        ),
        migrations.CreateModel(
            name="defectTypeThreshold",
            fields=[
                (
                    "sDefectTypeThresholdID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("sSeverity", models.CharField(max_length=30)),
                ("sLengthThreshold", models.FloatField()),
                ("sWidthhThreshold", models.FloatField()),
                ("sDepthThreshold", models.FloatField()),
                (
                    "sThresholdDefectTypeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.defecttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="defect",
            fields=[
                ("sDefectID", models.AutoField(primary_key=True, serialize=False)),
                ("sDefectTimeStamp", models.DateTimeField(blank=True)),
                ("sLength", models.FloatField()),
                ("sWidth", models.FloatField()),
                ("sDepth", models.FloatField()),
                ("sDistanceFromStartPoint", models.FloatField()),
                ("sSpeed", models.FloatField()),
                ("sDefectPhotoLocation", models.CharField(max_length=200)),
                (
                    "sDefectDefectTypeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.defecttype",
                    ),
                ),
                (
                    "sDefectHandrailID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.handrail",
                    ),
                ),
            ],
        ),
    ]
