# Generated by Django 4.2.7 on 2024-02-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="sSeverity",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
