# Generated by Django 4.2.7 on 2024-03-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_defect_sseverity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defecttype",
            name="sDefectTypeID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Defect Type ID"
            ),
        ),
        migrations.AlterField(
            model_name="defecttype",
            name="sDefectTypeName",
            field=models.CharField(max_length=30, verbose_name="Defect Type"),
        ),
        migrations.AlterField(
            model_name="defecttypethreshold",
            name="sDefectTypeThresholdID",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="#"),
        ),
        migrations.AlterField(
            model_name="defecttypethreshold",
            name="sDepthThreshold",
            field=models.FloatField(verbose_name="Depth Threshold"),
        ),
        migrations.AlterField(
            model_name="defecttypethreshold",
            name="sLengthThreshold",
            field=models.FloatField(verbose_name="Length Threshold"),
        ),
        migrations.AlterField(
            model_name="defecttypethreshold",
            name="sSeverity",
            field=models.CharField(max_length=30, verbose_name="Severity"),
        ),
        migrations.AlterField(
            model_name="defecttypethreshold",
            name="sThresholdDefectTypeID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.defecttype",
                verbose_name="Defect Type ID",
            ),
        ),
        migrations.AlterField(
            model_name="defecttypethreshold",
            name="sWidthhThreshold",
            field=models.FloatField(verbose_name="Width Threshold"),
        ),
        migrations.AlterField(
            model_name="handrail",
            name="sEscNo",
            field=models.CharField(max_length=50, verbose_name="Escalator No."),
        ),
        migrations.AlterField(
            model_name="handrail",
            name="sHandrailID",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, verbose_name="#"
            ),
        ),
    ]
