# Generated by Django 4.2.7 on 2024-03-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_alter_defecttype_sdefecttypeid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handrail",
            name="sHandrailID",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="#"),
        ),
    ]
